---
- hosts: prod_sclbuilder_db
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - git
        - nginx
        

  tasks:
    - name: "clone sclbuilder-ui"
      - name: Git checkout
        ansible.builtin.git:
          repo: '
          dest: /opt/sclbuilder-ui
          version: release-0.22

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
