---

- name: Initial database seed
  hosts: 
  tasks:

  - name: Install
    ansible.builtin.package:
      name: 
        - python38-psycopg2
        - python38-pip
        - python38-devel
        - python3-requests
        - python38-requests
        - wget
        - rpm-build
        - scl-utils-build
        - scl-utils
        - help2man
        - unzip
        - openssl-devel
        - python3-sphinx
        - make
        - gcc
        - libffi-devel
        - openldap-devel
        - libxml2-devel
        - xmlsec1-devel 
        - xmlsec1-openssl-devel
      state: present
  - name: Install bottle python package
    pip:
      name: 
        - requests
        - requirements-parser
        - spec2scl
        - setuptools_rust
        - wheel

  - name: Correct python3
    community.general.alternatives:
      name: python3
      path: /usr/bin/python3.8

    