---

- name: Setup a project in prod_sclbuilder_worker
  hosts: sclbuilder
  vars:
    organisation: "miracle"
    project: "awxrpm"
    version: "1.0.0"
    description: "Miracle supported awx installed with software collections"

  tasks:
  - name: Check if it already exists
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_subproject where subprojectprojectname = '{{ project }}';
    register: myproject 
    become: yes
    become_user: sclbuilder
  
  - name: insert when missing
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        INSERT INTO projects_project (
        projectname, 
        projectversion, 
        projectstatus, 
        projectdescription, 
        projectcreated 
        )
        VALUES (
        '{{ project }}',
        '{{ version }}',
        'Initial',
        '{{ description }}',
        '{{ ansible_date_time.date }} '
        );
    register: insertproject
    become: yes
    become_user: sclbuilder
