---
- name: Initial database seed
  hosts: prod_awx
  vars:
    - organisation: "miracle"
    - myrepo: "https://github.com/ansible/awx.git"
    - project: "awxrpm"
    - version: "19.4.0"
    - scl_version: "19.4.0"
    - scl_release: "1"
    - scl_description: "Miracle supported awx"
    - projectdir: "/root/{{ organisation }}/{{ project }}/{{ version }}"
    - specdir: "/root/rpmbuild/SPECS"
    - requirementfile: "{{ organisation }}-{{ project }}-{{ version }}.requirements.txt"
    - metaspecfile: "{{ organisation }}-{{ project }}.meta.scl.spec"

  tasks:
  - name: Install rhel
    ansible.builtin.package:
      name: 
        - redis
        - python38-pip
        - python38-devel
        - python3-devel
        - python3-requests
        - python38-requests
        - wget
        - rpm-build
        - scl-utils-build
        - scl-utils
        - help2man
        - unzip
        - openssl-devel
        - libtool-ltdl-devel
        - python3-sphinx
        - make
        - gcc
        - libffi-devel
        - openldap-devel
        - libxml2-devel
        - xmlsec1-devel 
        - xmlsec1-openssl-devel
        - libpq-devel
        - platform-python-devel
        - git
      state: present

  - name: Correct python3
    community.general.alternatives:
      name: python3
      path: /usr/bin/python3.8

  - name: Install bottle python package
    pip:
      name: 
        - requests
        - requirements-parser
        - spec2scl
        - setuptools_rust
        - wheel


  - name: "generate SSH key {{ ssh_key_filename }}"
    openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
    become: True

  - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
    ansible.builtin.fetch:
      src: ~/.ssh/id_rsa.pub
      dest: /var/lib/fetched
    become: True
  
  - name:  create ssh config
    ansible.builtin.template:
      src: sshconfig.j2
      dest: /root/.ssh/config
      mode: 600
      force: yes
    become: True

  - name: Install psyorg in the platforn python
    command: /usr/libexec/platform-python -m pip install psycopg2-binary 
    become: True

  - name: Add the user 'sclbuilder'
    ansible.builtin.user:
      name: sclbuilder
      comment: service account for scl create
    become: True

  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_host: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name:  create_specfiles | create a tailored script
    ansible.builtin.template:
      src: create.sclspec.sh.j2
      dest: /usr/local/bin/create.sclspec.sh
      mode: 755
      force: yes
    become: True
  
  - name: Creates directory rpmbuild
    file:
      path: "/root/rpmbuild/{{ item }}"
      state: directory
    become: True
    loop: 
      - SOURCES 
      - SPECS 
      - RPMS 
      - SRPMS 

  - name: Creates directory for project
    file:
      path: "/root/{{ organisation }}/{{ project }}/{{ version }}"
      state: directory

  - name: Download requirementfile
    get_url:
      url: "http://repos.pip2scl.dk/REQUIREMENTS/{{ requirementfile }}"
      dest: "{{ projectdir }}/{{ requirementfile }}"
      mode: '0440'
    become: True
   
  - name: Download 
    get_url:
      url: "http://repos.pip2scl.dk/SPECS/{{ metaspecfile }}"
      dest: "{{ specdir }}/{{ metaspecfile }}"
      mode: '0440'
    become: True
   
