---

- name: Initial database seed
  hosts: prod_sclbuilder_worker
  tasks:
  - name: Simple select query to sclbuilder db
    postgresql_query:
      db: sclbuilder
      login_host: "prod_sclbuilder_db"
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_host: "prod_sclbuilder_db"
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        INSERT INTO projects_package 
        (
          slug,
          packagename,
          packageversion, 
          packagestatus,  
          packagecreated
        ) 
        VALUES
        ( 
          '{{ slug }}',
          '{{ name }}',
          '{{ version }}',
          'Initial',
          '{{ ansible_date_time.date }} '
        )
        ON CONFLICT (slug) DO NOTHING;
    become: yes
    become_user: sclbuilder


